#!/bin/sh

DAEMON=python
DAEMON_ARGS="/root/robot/main.py"

start() {
	printf 'Starting %s: ' "$DAEMON_ARGS"
	if start-stop-daemon -S -q -b -x "$DAEMON" -- $DAEMON_ARGS; then
		echo "OK"
	else
		echo "FAIL"
	fi
}

stop() {
	printf 'Stopping %s\n' "$DAEMON_ARGS"
	kill `ps | grep python | grep robot | awk '{print $1}'`
}

restart() {
	stop
	start
}

case "$1" in
	start|stop|restart)
		"$1"
		;;
	reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac

exit $?
