#! /bin/sh -e
### BEGIN INIT INFO
# Provides:          udprelay
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: dump udp relay
### END INIT INFO
set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
DAEMON=/usr/bin/python3
PIDFILE=/tmp/udprelay.pid
DAEMON_ARGS="/home/administrator/udprelay.py 5005 5006"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting udprelay" "udprelay"
	/usr/sbin/start-stop-daemon --start --pidfile $PIDFILE -b --make-pidfile --exec "$DAEMON" -- $DAEMON_ARGS
	log_end_msg $?
    ;;
  stop)
	log_daemon_msg "Stopping udprelay" "udprelay"
	killproc -p $PIDFILE $DAEMON
	log_end_msg $?
    ;;
  status)
	if pidofproc -p $PIDFILE $DAEMON >/dev/null 2>&1; then
	    echo "$DAEMON is running";
	    exit 0;
	else
	    echo "$DAEMON is NOT running";
	    if test -f $PIDFILE; then exit 2; fi
	    exit 3;
	fi
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/udprelay {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
